FROM golang:1.25 AS builder
WORKDIR /app
COPY . .
RUN go mod tidy && go build -o main .

FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates curl && update-ca-certificates
COPY --from=builder /app/main .
COPY key.json /app/key.json
EXPOSE 6380 6381 9090
CMD ["./main"]


#docker buildx create --use --name RapidStore || docker buildx use Rapidbuilder-instance
#docker buildx build --no-cache --platform linux/amd64,linux/arm64 -t rich329/rapid-instance:v0.1.15 --push .

# docker pull rich329/rapid-instance:v0.1.15
# docker run -d -p 6380:6380 -p 6381:6381 -p 9090:9090 --name rapid-instance rich329/rapid-instance:v0.1.15

# docker rm -f rapid-instance
# docker build -t rich329/rapid-instance:v0.0.1 .