ServerConfig:
  address: "10.0.0.1"
  port: 6379
  health_check_port: 8079
  max_clients: 1500
  timeout: "50s"
  idle_timeout: "750s"
PersistenceConfig:
  wal_sync_interval: "4s"
  wal_path: "./staging_wal.log"
  wal_max_size: 15728640
MonitoringConfig:
  metrics_port: 9393
  metrics_path: "/staging/metrics"
  metrics_interval: "2s"
  log_file: "./staging.log"
ElectionConfig:
  zookeeper_servers:
    - "staging1:2181"
    - "staging2:2181"
    - "staging3:2181"
    - "staging4:2181"
  election_path: "/staging/leader"
  node_id: "staging-node-1"
  timeout: "20s"
