FROM golang:latest

WORKDIR /app

COPY . .
RUN go mod tidy
RUN go build -o main .
EXPOSE 3333

CMD ["./main"]


#docker buildx create --use --name RapidStore || docker buildx use Rapidbuilder-instance
#docker buildx build --no-cache --platform linux/amd64,linux/arm64 -t rich329/rapid-instance:v0.0.0 --push .

# docker pull rich329/rapid-instance:v0.0.0
# docker run -d -p 3333:3333 --name rapid-instance rich329/rapid-instance:v0.0.0
# docker rm -f rapid-instance
# docker build -t rich329/rapid-instance:v0.0.0 .